# from os.path import dirname, basename, isfile
# import glob
#
# modules = glob.glob(dirname(__file__) + "/*.py")
# __all__ = [basename(f)[:-3] for f in modules if isfile(f)]


__all__ = [
	'about',
	'account',
	'add_business',
	'admin',
	'bank_account',
	'bank_account_select',
	'business_details',
	'business_prefilled',
	'business_settings',
	'contact_flow',
	'contact_us',
	'disclosure',
	'eHome',
	'employee_add',
	'employee_add_csv',
	'employee_view',
	'employee_welcome',
	'employees',
	'enroll_accept',
	'enroll_code',
	'enroll_factor2',
	'enroll_name',
	'enroll_password',
	'enroll_signin',
	'for_employees',
	'for_employers',
	'invite',
	'invitation_card',
	'invitations',
	'invite_pre_screen',
	'lobby',
	'participate',
	'pay_election',
	'pay_election_history',
	'pending_elections',
	'personal_settings',
	'ps_add_email',
	'ps_add_phone',
	'ps_change_pw',
	'ps_confirmation',
	'ps_edit_email',
	'ps_edit_phone',
	'ps_employers',
	'pub_privacy',
	'pub_terms',
	'recipient',
	'recipient_address',
	'recipient_info',
	'recipient_name',
	'recipient_view',
	'reset_password',
	'send',
	'send_to_atm',
	'send_to_bank',
	'send_to_cashout',
	'signin',
	'signin_code',
	'td',
	'what_is_clabe',
	'why'
]
